name: Java CI with Gradle
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17 for Gradle execution 
      uses: actions/setup-java@v4
      with:
        java-version: '17' 
        distribution: 'temurin'
        cache: 'gradle'
    - name: Build with Gradle
      run: gradle build
    - name: Run tests with Gradle
      run: gradle test
